// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Wed Jun 22 14:32:08 2022

traffic_led traffic_led_inst
(
	.sys_clk(sys_clk_sig) ,	// input  sys_clk_sig
	.sys_rst_n(sys_rst_n_sig) ,	// input  sys_rst_n_sig
	.key(key_sig) ,	// input [3:0] key_sig
	.bit(bit_sig) ,	// output [7:0] bit_sig
	.segment(segment_sig) ,	// output [7:0] segment_sig
	.led(led_sig) 	// output [23:0] led_sig
);
